### ISSUE TITLE
Filtering by a label_field in a unique dimension shouldn't specify .label in the string e.g. column.label

### ISSUE THREAD

**Issue by mikeengland** [kayak/fireant#20]
Specifying column_name.label in a filter definition makes sense when the key is a column name, however as the key can be any unique value e.g. a hyperlinked URL or a unique ID, calling .label on this to specify that you want to filter on a label would be strange.

Example: `dimension_filters=[WildcardFilter('account.label', 'nam%')]`

**Comment by twheys** [comment]
This has be renamed to `account.display` per your other ticket.  The unique dimension can have any expression as a definition and/or a display_field.  If you use a a filter, the resulting value of the definition is filtered, not some column.  Using `account.label` tells the filter to filter on the account's display field instead of it's definition.
